spring.application.name=mobile-app-ws
spring.datasource.username=neco
spring.datasource.password=gediklineco61
#spring.datasource.url=jdbc:mysql://localhost:3306/photo_app
spring.jpa.hibernate.ddl-auto=update
server.error.include-stacktrace=never
server.error.include-message=always
tokenSecret=jf9i4jgu83nfl0jf9i4jgu83nfl0jf9i4jgu83nfl0jf9i4jgu83nfl0jf9i4jgu83nfl0jf9i4jgu83nfl0
server.servlet.context-path=/mobile-app-ws
server.port = 8080
spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console (this is default path for h2 console by the way)
spring.datasource.url=jdbc:h2:mem:testdb

#These are for logging sql queries and their values in the console.

#This line will enable sql queries and you will be able to see them in the console when you run the project.
logging.level.org.hibernate.SQL=DEBUG

#This line will make the values that are being used in those prepared sql statements visible.(positional parameters and named parameters.)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#This line is optional. It will make printed sql queries nicely formatted in the console. They will be easier to read.
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

# Specify the path of the OpenAPI documentation
springdoc.api-docs.path=/api-docs

# Specify the path of the Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true